### ISSUE TITLE
Blu_Schedutil Tunables

### ISSUE THREAD

**Issue by JBolho** [JBolho/JBH9#1]
Apparently the governor is successfully ported for hi3660, but tunables are not accessible and it's default behaviour sets the frequencies almost glued to max. If someone can help, it would be appreciated.

**Comment by Dil3mm4** [comment]
@engstk you may want to have a word on that

**Comment by JBolho** [comment]
Issue fixed, corrected mistake on sugov_init parameters. Also, behaviour is due to "stune.boost" parameters, which is controllable with profiling.
